### ISSUE TITLE
Add getallheaders alternative

### ISSUE THREAD

**Issue by white-gecko** [AKSW/xodx#1]
Implement a `getallheaders` alternative to be used on nginx. See also: http://php.net/manual/function.getallheaders.php

**Comment by white-gecko** [comment]
Fixed with PHP 5.4:
http://www.php.net/ChangeLog-5.php#5.4.0

**Comment by white-gecko** [comment]
It is still not available for php-fpm. See https://bugs.php.net/bug.php?id=62596.

**Comment by CMCDragonkai** [comment]
How did you resolve this?
