### ISSUE TITLE
Users with wrong (even invalid) URI

### ISSUE THREAD

**Issue by hg-graebe** [AKSW/xodx#26]
During "friending" one can supply a bare string that is not converted to a valid URI. This crashes the Ontowiki interface.

Put to http://leipzig-data.de:8891/sparql the query
select \* where { ?s foaf:knows ?t }
to see the wrong values ?t="test" and ?t="kujawa".

I have no idea how to label this issue as "bug" as desired in the "Issue workflow section".

**Comment by white-gecko** [comment]
We have to check incoming URIs with the according Erfurt method.
